# Generated by Django 3.2 on 2022-06-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('profile_photo', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
